apiVersion: v1
kind: Pod
metadata:
  name: config-test-pod
  labels:
    app: config-test
spec:
  containers:
    - name: test-app
      image: alpine:latest
      command: ["sh", "-c", "sleep 3600"]
      envFrom:
        - configMapRef:
            name: yatri-app-config
