apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  labels:
    app: secret-test
spec:
  containers:
    - name: test-app
      image: alpine:latest
      command: ["sh", "-c", "sleep 3600"]
      envFrom:
        - secretRef:
            name: yatri-db-secret
